variables:
  LATEX_IMAGE: listx/texlive:2020

build:
  image: $LATEX_IMAGE
  script:
    - latexmk -bibtex -pdf -pdflatex="pdflatex -interaction=nonstopmode" main.tex

  artifacts:
    paths:
      - "*.pdf"
