variables:
  LATEX_IMAGE: texlive/texlive:latest

build:
  image: $LATEX_IMAGE
  script:
    - ls
    - pwd
    - git status
    - git rev-parse --short HEAD
    - latexmk -bibtex -pdf -shell-escape

  artifacts:
    paths:
      - "*.pdf"
